ossim/job/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns =[

]

ossim/mat/urls.py
from django.conf.urls import url
from mat import views

app_name = 'mat'

urlpatterns = [
    url(r'^$',views.home_page, name="home"),
    url(r'^mft/$', views.mat_mft_get_data, name="mat-get-data"),
    url(r'^mvt/$', views.mat_mvt_get_data, name="mvt-get-data"),
]

ossim/ossim/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^job/', include('job.urls')),
    url(r'^disk/', include('disk.urls')),
    url(r'^synchro/', include('synchro.urls')),
    url(r'^process/', include('process.urls')),
    url(r'^memory/', include('memory.urls')),
    url(r'^matdemo/', include('mat.urls')),
    url(r'^mat/', views.matindex),
    url(r'^filesystem/', include('filesystem.urls')),
    url(r'^wiki/', include('wikipages.urls')),
]

ossim/mat/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import loader
import json

def home_page(request):
    return render(request, 'mat/index.html')

def mat_mft_get_data(request):
    variables = ['total_memory', 'no_of_blocks']
    submitted = True
    context = {}
    block_size = [0,1,2,3,4,5,6,7,8,0,1,1,1,1,1]
    context['invalid_data'] = False
    for x in variables:
        submitted = request.POST.get(x,False)
        if submitted is False:
            print("Hello")
            break
        else:
            try:
                context[x] = int(request.POST.get(x))
            except ValueError:
                context['invalid_data'] = True
                break

    if context['invalid_data'] is False and submitted:
        for i in range(1, context['no_of_blocks']+1):
            block_size[i] = request.POST.get('block_size_' + str(i))
        context['block_size'] = json.dumps(block_size)

    if submitted is False or context['invalid_data'] is True:
        return render(request, 'mat/mft/get_data.html', context)
    else:
        return render(request, 'mat/mft/show_demo.html', context)

def mat_mvt_get_data(request):
    if request.POST:
        context = {
            'totalMemory' : request.POST['total_memory'],
            'inputMemory' : request.POST['input_memory']
        }
        return render(request, 'mat/mvt/show_demo.html', context)
    return render(request, 'mat/mvt/get_data.html')

ossim/ossim/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse


def index(request):
    return render(request, 'ossim/index.html')

def matindex(request):
    return render(request, 'mat/mainindex.html')

ossim/ossim/templates/mat/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>
        Memory Allocation Techniques
    </title>


    <!-- CSS Additional Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


    <!-- JavaScript Additional Files -->
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</head>
<body>
<div class="container-fluid">
    <div id="top-content">
        <h1 id="page-heading">
            Memory Management Techniques
        </h1>
    </div>
    <div id="middle-content" style="margin-top:15%;">
        <h3 style="text-align: center">What do you want to see?</h3>
        <br>
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-3" style="text-align: center;">
                <a href="{% url 'mat:mat-get-data' %}">
                <div id="link" style="margin-left: 25%;">
                    <h3>MFT</h3>
                </div>
                </a>
            </div>
            <div class="col-sm-3" style="text-align: center;">
                <a href="{% url 'mat:mvt-get-data' %}">
                <div id="link" style="margin-left:25%;">
                    <h3>MVT</h3>
                </div>
                </a>
            </div>
        </div>
    </div>
</div>
</body>
</html>

ossim/ossim/templates/mat/mainindex.html
<html>
	<head>
		<title>Memory Allocation</title>
		<script src="https://code.jquery.com/jquery-3.1.0.min.js"
            integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s="
            crossorigin="anonymous">
        </script>
        {% load static %}
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<link href="{%static 'filesystem/styles.css' %}" rel="stylesheet" type="text/css" />
	</head>
	<body>
		<nav role="navigation" class="navbar navbar-default">
		    <div id="navbarCollapse" class="collapse navbar-collapse">
		        <ul class="nav navbar-nav">
		            <li><a href="/">Home</a></li>
		            <li><a href="/process/">Process Scheduling</a></li>
		            <li><a href="/memory/page/">Page Replacement</a></li>
		            <li><a href="/disk/">Disk Scheduling</a></li>
		            <li><a href="/synchro/semaphores/">Semaphores</a></li>
		            <li><a href="/synchro/socket/">Sockets</a></li>
		            <li><a href="/filesystem/">File Structure</a></li>
		            <li class="active"><a href="/mat/">Memory Allocation</a></li>
					<li><a href="/synchro/deadlocks/">Banker's Algorithm</a></li>
		        </ul>
		    </div>
		</nav>
		<h1>Memory Allocation</h1>
		<div id="choice">
			<ul id="ulchoice">
					<a href="/matdemo"><li id="lichoice">Demo</li></a>
					<a href="/wiki/mem"><li id="wikichoice">Wiki</li></a>
			</ul>
		</div>
	</body>
</html>